language: java
jdk:
 - oraclejdk7
 - openjdk7

before_script:
 - npm install -g gulp
 - npm install
script: gulp

notifications:
 email:
  recipients:
   - marcusvinicius30798@gmail.com
   - yagolasse@gmail.com
   - arthur1503@gmail.com

  on_success: always
