language: java

services:
  - postgresql

addons:
  - postgresql: "9.3"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

notifications:
 email:
  recipients:
   - marcusvinicius30798@gmail.com
   - yagolasse@gmail.com
   - arthur1503@gmail.com

  on_success: always
