INSERT INTO state VALUES (default, 'Acre');
INSERT INTO state VALUES (default, 'Alagoas');
INSERT INTO state VALUES (default, 'Amazonas');
INSERT INTO state VALUES (default, 'Amapá');
INSERT INTO state VALUES (default, 'Bahia');
INSERT INTO state VALUES (default, 'Ceará');
INSERT INTO state VALUES (default, 'Distrito Federal');
INSERT INTO state VALUES (default, 'Espírito Santo');
INSERT INTO state VALUES (default, 'Goiás');
INSERT INTO state VALUES (default, 'Maranhão');
INSERT INTO state VALUES (default, 'Minas Gerais');
INSERT INTO state VALUES (default, 'Mato Grosso do Sul');
INSERT INTO state VALUES (default, 'Mato Grosso');
INSERT INTO state VALUES (default, 'Pará');
INSERT INTO state VALUES (default, 'Paraíba');
INSERT INTO state VALUES (default, 'Pernambuco');  
INSERT INTO state VALUES (default, 'Piauí');  
INSERT INTO state VALUES (default, 'Paraná');  
INSERT INTO state VALUES (default, 'Rio de Janeiro');  
INSERT INTO state VALUES (default, 'Rio Grande do Norte');  
INSERT INTO state VALUES (default, 'Rondônia');  
INSERT INTO state VALUES (default, 'Roraima');  
INSERT INTO state VALUES (default, 'Rio Grande do Sul');  
INSERT INTO state VALUES (default, 'Santa Catarina');  
INSERT INTO state VALUES (default, 'Sergipe');  
INSERT INTO state VALUES (default, 'São Paulo');  
INSERT INTO state VALUES (default, 'Tocantins');  
